from constants import *

OLD_TESTS_COMBOS = {

    'vg_pose01': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[-0.7366, 1.4478]],
        'init_polar': [[-0.7366, 1.4478]],
        'fin_cartesian': [[-0.7366, 1.4478]],
        'fin_polar': [[-0.7366, 1.4478]]
    },

    'vg_pose02': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[-0.7366, 1.8161]],
        'init_polar': [[-0.7366, 1.8161]],
        'fin_cartesian': [[-0.7366, 1.8161]],
        'fin_polar': [[-0.7366, 1.8161]]
    },

    'vg_pose03': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[-0.7366, 2.225]],
        'init_polar': [[-0.7366, 2.225]],
        'fin_cartesian': [[-0.7366, 2.225]],
        'fin_polar': [[-0.7366, 2.225]]
    },

    'vg_pose04': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[-0.7366, 2.489]],
        'init_polar': [[-0.7366, 2.489]],
        'fin_cartesian': [[-0.7366, 2.489]],
        'fin_polar': [[-0.7366, 2.489]]
    },

    'vg_pose05': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_polar': [[-0.7366, 2.8956]],
        'init_cartesian': [[-0.7366, 2.8956]],
        'fin_polar': [[-0.7366, 2.8956]],
        'fin_cartesian': [[-0.7366, 2.8956]]
    },

    'vg_pose06': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_pose07': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[1.003, 2.8956]],
        'init_polar': [[1.003, 2.8956]],
        'fin_cartesian': [[1.003, 2.8956]],
        'fin_polar': [[1.003, 2.8956]]
    },

    'vg_pose08': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 0.7112]],
        'init_polar': [[0.127, 0.7112]],
        'fin_cartesian': [[0.127, 0.7112]],
        'fin_polar': [[0.127, 0.7112]]
    },

    'vg_pose09': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[-0.7366, 0.7112]],
        'init_polar': [[-0.7366, 0.7112]],
        'fin_cartesian': [[-0.7366, 0.7112]],
        'fin_polar': [[-0.7366, 0.7112]]
    },

    'vg_pose10': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 3.711]],
        'init_polar': [[0.127, 3.711]],
        'fin_cartesian': [[0.127, 3.711]],
        'fin_polar': [[0.127, 3.711]]
    },

    'vg_orient_north': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_orient_east': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_orient_west': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_orient_south': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'stationary',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_straight_north': {
        'integration': True,
        'time': 10.00,
        'type': 'moving',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 3.457]],
        'fin_polar': [[0.127, 3.457]]
    },

    'vg_straight_east': {
        'integration': True,
        'time': 10.00,
        'type': 'moving',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[1.3716, 2.225]],
        'fin_polar': [[1.3716, 2.225]]
    },

    'vg_straight_west': {
        'integration': True,
        'time': 10.00,
        'type': 'moving',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[-1.1176, 2.225]],
        'fin_polar': [[-1.1176, 2.225]]
    },

    'vg_straight_south': {
        'integration': True,
        'time': 10.00,
        'type': 'moving',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 0.9144]],
        'fin_polar': [[0.127, 0.9144]]
    },

    'vg_full_rotate_acw': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 50.00,
        'type': 'rotating',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_full_rotate_cw': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 50.00,
        'type': 'rotating',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_rotate_acw': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'rotating',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vg_rotate_cw': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'rotating',
        'odom_positions': BOT_NAMES['g'] + ODOM_POSITIONS,
        'odom_velocities': BOT_NAMES['g'] + ODOM_VELOCITIES,
        'odom_dcm': BOT_NAMES['g'] + ODOM_DCM,
        'odom_quaternions': BOT_NAMES['g'] + ODOM_QUATERNIONS,
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225]],
        'init_polar': [[0.127, 2.225]],
        'fin_cartesian': [[0.127, 2.225]],
        'fin_polar': [[0.127, 2.225]]
    },

    'vbg_pose06_pose01_same': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'rotating',
        'odom_positions': [
            BOT_NAMES['b'] + ODOM_POSITIONS,
            BOT_NAMES['g'] + ODOM_POSITIONS
        ],
        'odom_velocities': [
            BOT_NAMES['b'] + ODOM_VELOCITIES,
            BOT_NAMES['g'] + ODOM_VELOCITIES
        ],
        'odom_dcm': [
            BOT_NAMES['b'] + ODOM_DCM,
            BOT_NAMES['g'] + ODOM_DCM
        ],
        'odom_quaternions': [
            BOT_NAMES['b'] + ODOM_QUATERNIONS,
            BOT_NAMES['g'] + ODOM_QUATERNIONS
        ],
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'init_polar': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_polar': [[0.127, 2.225], [-0.7366, 1.4478]]
    },

    'vbg_pose06_pose01_opp': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'rotating',
        'odom_positions': [
            BOT_NAMES['b'] + ODOM_POSITIONS,
            BOT_NAMES['g'] + ODOM_POSITIONS
        ],
        'odom_velocities': [
            BOT_NAMES['b'] + ODOM_VELOCITIES,
            BOT_NAMES['g'] + ODOM_VELOCITIES
        ],
        'odom_dcm': [
            BOT_NAMES['b'] + ODOM_DCM,
            BOT_NAMES['g'] + ODOM_DCM
        ],
        'odom_quaternions': [
            BOT_NAMES['b'] + ODOM_QUATERNIONS,
            BOT_NAMES['g'] + ODOM_QUATERNIONS
        ],
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'init_polar': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_polar': [[0.127, 2.225], [-0.7366, 1.4478]]
    },

    'vbg_rotate_acw_same': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'rotating',
        'odom_positions': [
            BOT_NAMES['b'] + ODOM_POSITIONS,
            BOT_NAMES['g'] + ODOM_POSITIONS
        ],
        'odom_velocities': [
            BOT_NAMES['b'] + ODOM_VELOCITIES,
            BOT_NAMES['g'] + ODOM_VELOCITIES
        ],
        'odom_dcm': [
            BOT_NAMES['b'] + ODOM_DCM,
            BOT_NAMES['g'] + ODOM_DCM
        ],
        'odom_quaternions': [
            BOT_NAMES['b'] + ODOM_QUATERNIONS,
            BOT_NAMES['g'] + ODOM_QUATERNIONS
        ],
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'init_polar': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_polar': [[0.127, 2.225], [-0.7366, 1.4478]]
    },

    'vbg_rotate_cw_opp': {
        'integration': False,
        'polar': False,
        'wall_gating_dist': WALL_DIST_M,
        'time': 10.00,
        'type': 'rotating',
        'odom_positions': [
            BOT_NAMES['b'] + ODOM_POSITIONS,
            BOT_NAMES['g'] + ODOM_POSITIONS
        ],
        'odom_velocities': [
            BOT_NAMES['b'] + ODOM_VELOCITIES,
            BOT_NAMES['g'] + ODOM_VELOCITIES
        ],
        'odom_dcm': [
            BOT_NAMES['b'] + ODOM_DCM,
            BOT_NAMES['g'] + ODOM_DCM
        ],
        'odom_quaternions': [
            BOT_NAMES['b'] + ODOM_QUATERNIONS,
            BOT_NAMES['g'] + ODOM_QUATERNIONS
        ],
        'scan_values': SCAN_LOCATION['v'],
        'odom_offset_polar': [],
        'odom_offset_cartesian': [],
        'scan_offset_polar': [],
        'scan_offset_cartesian': [],
        'init_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'init_polar': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_cartesian': [[0.127, 2.225], [-0.7366, 1.4478]],
        'fin_polar': [[0.127, 2.225], [-0.7366, 1.4478]]
    }

}
