#!/usr/bin/env bash

REMOTE_NAME="indigo"

# set all necessary folders
LOCAL_BASE="$HOME/Dropbox/Lab/Turtlebot"
REMOTE_BASE="~/catkin_ws/src"

PACKAGE_FOLDER="multi_agent"
SCRIPTS_FOLDER=$PACKAGE_FOLDER/scripts
SOURCE_FOLDER=$PACKAGE_FOLDER/scripts/rosagent
EXE_FOLDER=$PACKAGE_FOLDER/scripts/exe
LAUNCH_FOLDER=$PACKAGE_FOLDER/launch
ARGS_FOLDER=$PACKAGE_FOLDER/scripts/args
INPUT_FOLDER=$PACKAGE_FOLDER/scripts/input
INCLUDE_FOLDER=$PACKAGE_FOLDER/include
ROS_SRC_FOLDER=$PACKAGE_FOLDER/src

DATA_SCRIPT="gather_data.sh"
PROCESS_SCRIPT="process.py"
GENERATE_SCRIPT="generate.py"
CONSTANTS_SCRIPT="constants.py"
SIMPLE_SCRIPT="simple_plot.py"
CMAKE_SCRIPT="CMakeLists.txt"
PACKAGE_SCRIPT="package.xml"

LICENSE_FILE="LICENSE"
README_FILE="README.rst"
SETUP_FILE="setup.py"

# create some executable scripts
echo "Create executable scripts ..."
chmod +x $LOCAL_BASE/$SCRIPTS_FOLDER/$SIMPLE_SCRIPT
chmod +x $LOCAL_BASE/$SCRIPTS_FOLDER/$GENERATE_SCRIPT
chmod +x $LOCAL_BASE/$SCRIPTS_FOLDER/$PROCESS_SCRIPT

# generate the required files
echo "Generating inputs and launch files ..."
python $LOCAL_BASE/$SCRIPTS_FOLDER/$GENERATE_SCRIPT

# copy all relevant folders
echo "Copying folders to remote base station ..."
scp -r $LOCAL_BASE/$INCLUDE_FOLDER $REMOTE_NAME:$REMOTE_BASE/$INCLUDE_FOLDER
scp -r $LOCAL_BASE/$ROS_SRC_FOLDER $REMOTE_NAME:$REMOTE_BASE/$ROS_SRC_FOLDER
scp -r $LOCAL_BASE/$LAUNCH_FOLDER/* $REMOTE_NAME:$REMOTE_BASE/$LAUNCH_FOLDER/
scp -r $LOCAL_BASE/$SOURCE_FOLDER/* $REMOTE_NAME:$REMOTE_BASE/$SOURCE_FOLDER/
scp -r $LOCAL_BASE/$EXE_FOLDER/* $REMOTE_NAME:$REMOTE_BASE/$EXE_FOLDER/
scp -r $LOCAL_BASE/$ARGS_FOLDER/* $REMOTE_NAME:$REMOTE_BASE/$ARGS_FOLDER/
scp -r $LOCAL_BASE/$INPUT_FOLDER/* $REMOTE_NAME:$REMOTE_BASE/$INPUT_FOLDER/

# copy all relevant files
echo "Copying scripts and files to remote base station ..."
scp $LOCAL_BASE/$PACKAGE_FOLDER/$CMAKE_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$PACKAGE_FOLDER/$CMAKE_SCRIPT
scp $LOCAL_BASE/$PACKAGE_FOLDER/$PACKAGE_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$PACKAGE_FOLDER/$PACKAGE_SCRIPT
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$DATA_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$DATA_SCRIPT
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$PROCESS_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$PROCESS_SCRIPT
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$GENERATE_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$GENERATE_SCRIPT
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$CONSTANTS_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$CONSTANTS_SCRIPT
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$SIMPLE_SCRIPT $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$SIMPLE_SCRIPT
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$LICENSE_FILE $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$LICENSE_FILE
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$README_FILE $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$README_FILE
scp $LOCAL_BASE/$SCRIPTS_FOLDER/$SETUP_FILE $REMOTE_NAME:$REMOTE_BASE/$SCRIPTS_FOLDER/$SETUP_FILE

echo "Remote base station setup complete."
